INSERT INTO `games` (`GAME_NAME`, `SLUG`, `PRIORITY`, `IS_ACTIVE`)
VALUES
  ('리그 오브 레전드', 'league-of-legends', 10, 'Y'),
  ('배틀그라운드', 'pubg', 20, 'Y'),
  ('발로란트', 'valorant', 30, 'Y'),
  ('로스트아크', 'lost-ark', 40, 'Y'),
  ('오버워치 2', 'overwatch-2', 50, 'Y')
ON DUPLICATE KEY UPDATE
  `GAME_NAME` = VALUES(`GAME_NAME`),
  `PRIORITY` = VALUES(`PRIORITY`),
  `IS_ACTIVE` = VALUES(`IS_ACTIVE`);

INSERT INTO `game_requirements`
  (`GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT `GAME_ID`, 'FHD', 144, 'HIGH', 50, 40, 16
FROM `games`
WHERE `SLUG` = 'league-of-legends'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN` = VALUES(`RAM_GB_MIN`);

INSERT INTO `game_requirements`
  (`GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT `GAME_ID`, 'FHD', 144, 'HIGH', 75, 80, 16
FROM `games`
WHERE `SLUG` = 'pubg'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN` = VALUES(`RAM_GB_MIN`);

INSERT INTO `game_requirements`
  (`GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT `GAME_ID`, 'FHD', 240, 'HIGH', 65, 50, 16
FROM `games`
WHERE `SLUG` = 'valorant'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN` = VALUES(`RAM_GB_MIN`);

INSERT INTO `game_requirements`
  (`GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT `GAME_ID`, 'QHD', 144, 'HIGH', 80, 85, 16
FROM `games`
WHERE `SLUG` = 'lost-ark'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN` = VALUES(`RAM_GB_MIN`);

INSERT INTO `game_requirements`
  (`GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT `GAME_ID`, 'FHD', 144, 'HIGH', 70, 70, 16
FROM `games`
WHERE `SLUG` = 'overwatch-2'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN` = VALUES(`RAM_GB_MIN`);
