-- 게임 마스터는 benchmark_games 단일 테이블로 통합됨 (2026-09-03)
-- 기존 games 테이블 + game_requirements seed는 아래로 교체

-- game_requirements: benchmark_games slug 기준으로 BENCHMARK_GAME_ID 조회하여 삽입
INSERT INTO `game_requirements`
  (`BENCHMARK_GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT bg.`BENCHMARK_GAME_ID`, 'FHD', 144, 'HIGH', 50, 40, 16
FROM `benchmark_games` bg WHERE bg.`GAME_NAME` = '리그오브레전드'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN`    = VALUES(`RAM_GB_MIN`);

INSERT INTO `game_requirements`
  (`BENCHMARK_GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT bg.`BENCHMARK_GAME_ID`, 'FHD', 144, 'HIGH', 75, 80, 16
FROM `benchmark_games` bg WHERE bg.`GAME_NAME` = '배틀그라운드'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN`    = VALUES(`RAM_GB_MIN`);

INSERT INTO `game_requirements`
  (`BENCHMARK_GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT bg.`BENCHMARK_GAME_ID`, 'FHD', 240, 'HIGH', 65, 50, 16
FROM `benchmark_games` bg WHERE bg.`GAME_NAME` = '발로란트'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN`    = VALUES(`RAM_GB_MIN`);

INSERT INTO `game_requirements`
  (`BENCHMARK_GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT bg.`BENCHMARK_GAME_ID`, 'QHD', 144, 'HIGH', 80, 85, 16
FROM `benchmark_games` bg WHERE bg.`GAME_NAME` = '로스트아크'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN`    = VALUES(`RAM_GB_MIN`);

INSERT INTO `game_requirements`
  (`BENCHMARK_GAME_ID`, `RESOLUTION`, `TARGET_FPS`, `QUALITY_PRESET`, `CPU_SCORE_MIN`, `GPU_SCORE_MIN`, `RAM_GB_MIN`)
SELECT bg.`BENCHMARK_GAME_ID`, 'FHD', 144, 'HIGH', 70, 70, 16
FROM `benchmark_games` bg WHERE bg.`GAME_NAME` = '오버워치2'
ON DUPLICATE KEY UPDATE
  `CPU_SCORE_MIN` = VALUES(`CPU_SCORE_MIN`),
  `GPU_SCORE_MIN` = VALUES(`GPU_SCORE_MIN`),
  `RAM_GB_MIN`    = VALUES(`RAM_GB_MIN`);
