CREATE TABLE IF NOT EXISTS `user_cart_quotes` (
  `CART_QUOTE_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `USER_ID` BIGINT UNSIGNED NOT NULL,
  `CLIENT_CART_ID` VARCHAR(120) NULL,
  `TITLE` VARCHAR(255) NULL,
  `TOTAL_PRICE` INT NOT NULL DEFAULT 0,
  `QUOTE_SNAPSHOT_JSON` JSON NOT NULL,
  `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DT` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CART_QUOTE_ID`),
  KEY `idx_user_cart_quotes_user` (`USER_ID`, `CREATED_DT`),
  UNIQUE KEY `uk_user_cart_client` (`USER_ID`, `CLIENT_CART_ID`),
  CONSTRAINT `fk_user_cart_quotes_user`
    FOREIGN KEY (`USER_ID`) REFERENCES `users` (`USER_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
