CREATE TABLE IF NOT EXISTS `recommendation_posts` (
  `RECOMMENDATION_POST_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `SLUG` VARCHAR(160) NOT NULL,
  `TITLE` VARCHAR(255) NOT NULL,
  `SUBTITLE` VARCHAR(255) NULL,
  `SUMMARY` TEXT NULL,
  `BODY_MD` MEDIUMTEXT NULL,
  `STATUS` VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
  `SOURCE_TYPE` VARCHAR(40) NOT NULL DEFAULT 'JHS_MANUAL',
  `SOURCE_BENCHMARK_BUILD_ID` BIGINT NULL,
  `TARGET_BUDGET` INT NULL,
  `TOTAL_PRICE` INT NOT NULL DEFAULT 0,
  `PURPOSE` VARCHAR(40) NOT NULL DEFAULT 'GAME',
  `CPU_BRAND` VARCHAR(40) NULL,
  `GPU_BRAND` VARCHAR(40) NULL,
  `CPU_MODEL` VARCHAR(120) NULL,
  `GPU_MODEL` VARCHAR(120) NULL,
  `COMBO_TYPE` VARCHAR(60) NULL,
  `THUMBNAIL_IMAGE_URL` VARCHAR(1000) NULL,
  `CASE_PART_NAME` VARCHAR(700) NULL,
  `POPULARITY_SCORE` INT NOT NULL DEFAULT 0,
  `VIEW_COUNT` INT NOT NULL DEFAULT 0,
  `CART_COUNT` INT NOT NULL DEFAULT 0,
  `ORDER_COUNT` INT NOT NULL DEFAULT 0,
  `PUBLISHED_DT` DATETIME NULL,
  `RAW_JSON` JSON NULL,
  `CREATED_DT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DT` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`RECOMMENDATION_POST_ID`),
  UNIQUE KEY `uk_recommendation_posts_slug` (`SLUG`),
  KEY `idx_recommendation_posts_status_price` (`STATUS`, `TOTAL_PRICE`),
  KEY `idx_recommendation_posts_combo` (`CPU_BRAND`, `GPU_BRAND`),
  KEY `idx_recommendation_posts_models` (`CPU_MODEL`, `GPU_MODEL`),
  KEY `idx_recommendation_posts_popularity` (`STATUS`, `POPULARITY_SCORE`, `ORDER_COUNT`, `CART_COUNT`),
  KEY `idx_recommendation_posts_source_build` (`SOURCE_BENCHMARK_BUILD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `recommendation_post_parts` (
  `RECOMMENDATION_POST_PART_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RECOMMENDATION_POST_ID` BIGINT UNSIGNED NOT NULL,
  `PART_CATEGORY` VARCHAR(50) NOT NULL,
  `PART_LABEL` VARCHAR(80) NULL,
  `PART_NAME` VARCHAR(700) NOT NULL,
  `PART_PRICE` INT NOT NULL DEFAULT 0,
  `QUANTITY` INT NOT NULL DEFAULT 1,
  `PRODUCT_NO` VARCHAR(120) NULL,
  `IMAGE_URL` VARCHAR(1000) NULL,
  `SPEC_TEXT` TEXT NULL,
  `SORT_ORDER` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`RECOMMENDATION_POST_PART_ID`),
  KEY `idx_recommendation_post_parts_post` (`RECOMMENDATION_POST_ID`, `SORT_ORDER`),
  KEY `idx_recommendation_post_parts_category_name` (`PART_CATEGORY`, `PART_NAME`(120)),
  CONSTRAINT `fk_recommendation_post_parts_post`
    FOREIGN KEY (`RECOMMENDATION_POST_ID`) REFERENCES `recommendation_posts` (`RECOMMENDATION_POST_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `recommendation_post_games` (
  `RECOMMENDATION_POST_GAME_ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `RECOMMENDATION_POST_ID` BIGINT UNSIGNED NOT NULL,
  `GAME_NAME` VARCHAR(160) NOT NULL,
  `RESOLUTION` VARCHAR(20) NOT NULL DEFAULT 'FHD',
  `QUALITY_PRESET` VARCHAR(40) NULL,
  `FPS_MIN` INT NULL,
  `FPS_MAX` INT NULL,
  `COMFORT_GRADE` VARCHAR(40) NULL,
  PRIMARY KEY (`RECOMMENDATION_POST_GAME_ID`),
  KEY `idx_recommendation_post_games_post` (`RECOMMENDATION_POST_ID`),
  KEY `idx_recommendation_post_games_search` (`GAME_NAME`, `RESOLUTION`),
  CONSTRAINT `fk_recommendation_post_games_post`
    FOREIGN KEY (`RECOMMENDATION_POST_ID`) REFERENCES `recommendation_posts` (`RECOMMENDATION_POST_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
